### ISSUE TITLE
The 'google-api-core' distribution was not found and is required by the application 

### ISSUE THREAD

**Issue by Efrain73** [gee-community/qgis-earthengine-plugin#75]
After installing the plugin, I get this message, I did tests in several versions of Qgis and the message persists

--------------------------------------------------------------------------------------------------------------------

No se pudo cargar el complemento 'ee_plugin' debido a un error al llamar a su método classFactory() 

pkg_resources.DistributionNotFound: The 'google-api-core' distribution was not found and is required by the application 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/SIGYURY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 25, in classFactory
    from .ee_plugin import GoogleEarthEnginePlugin
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/SIGYURY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\ee_plugin.py", line 22, in 
    import ee
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\SIGYURY\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\__init__.py", line 17, in 
    from . import batch
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\SIGYURY\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\batch.py", line 15, in 
    from . import _cloud_api_utils
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\SIGYURY\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\_cloud_api_utils.py", line 22, in 
    from googleapiclient import discovery
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\SIGYURY\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\discovery.py", line 49, in 
    import google.api_core.client_options
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\SIGYURY\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\api_core\__init__.py", line 23, in 
    __version__ = get_distribution("google-api-core").version
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 472, in get_distribution
    dist = get_provider(dist)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 344, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'google-api-core' distribution was not found and is required by the application

Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versión de QGIS: 3.16.0-Hannover Hannover, 43b64b13f3 

Ruta de Python:
C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python
C:/Users/SIGYURY/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/SIGYURY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/SIGYURY/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\SIGYURY\AppData\Local\acatama\python37
C:\Users\SIGYURY\AppData\Local\acatama\python37\lib\site-packages
C:\Users\SIGYURY\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows

**Comment by XavierCLL** [comment]
Hi, this error was fixed (but not released yet) please test it using the following zip and installing it manually: https://drive.google.com/uc?export=download&id=1x8QCQ-5CzjQEk-cNEyMU87Xz5S8LaR7s

**Comment by Efrain73** [comment]
Thanks Xavier
*______________________________________    *
          *Efrain Y. Turpo Cayo*
*         Ing° Topógrafo y Agrimensor*
*   GIS, Remote Sensing and Environmental Modeling*
*___________________________________*


Em dom., 13 de dez. de 2020 às 19:44, Xavier C. Llano <
notifications@github.com> escreveu:

**Comment by XavierCLL** [comment]
You're welcome, I'm going to close this, open it again if the error persists

**Comment by Efrain73** [comment]
Hello
I still can't run the plugin
I get another error when executing this code example

# ----------------------------------------------------
import ee
from ee_plugin import Map

image = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR') \
          .filterDate('2018-01-01', '2018-12-02').median()

Map.addLayer(image,{'bands': ['B6', 'B5', 'B4'], 'min': 300, 'max': 5000},
'Landsat 2018')
# ---------------------------------------------------

error
/////////////////////////////////////////////
TypeError: createProvider() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\code.py", line 90, in
runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 8, in <module>
  File
"C:/Users/SIGYURY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\Map.py",
line 29, in addLayer
    ee_plugin.utils.add_or_update_ee_layer(eeObject, visParams, name,
shown, opacity)
  File
"C:/Users/SIGYURY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py",
line 133, in add_or_update_ee_layer
    update_ee_layer_properties(layer, eeObject, visParams, shown, opacity)
  File
"C:/Users/SIGYURY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py",
line 41, in update_ee_layer_properties
    layer.dataProvider().set_ee_object(eeObject)
AttributeError: 'NoneType' object has no attribute 'set_ee_object'
exec(open('C:/Users/SIGYURY/AppData/Local/Temp/tmp7ei3drtx.py'.encode('utf-8')).read())
TypeError: createProvider() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\code.py", line 90, in
runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 8, in <module>
  File
"C:/Users/SIGYURY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\Map.py",
line 29, in addLayer
    ee_plugin.utils.add_or_update_ee_layer(eeObject, visParams, name,
shown, opacity)
  File
"C:/Users/SIGYURY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py",
line 133, in add_or_update_ee_layer
    update_ee_layer_properties(layer, eeObject, visParams, shown, opacity)
  File
"C:/Users/SIGYURY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py",
line 41, in update_ee_layer_properties
    layer.dataProvider().set_ee_object(eeObject)
AttributeError: 'NoneType' object has no attribute 'set_ee_object'
  /////////////////////////////////////////////


*______________________________________    *
          *Efrain Y. Turpo Cayo*
*         Ing° Topógrafo y Agrimensor*
*   GIS, Remote Sensing and Environmental Modeling*
*___________________________________*


Em ter., 15 de dez. de 2020 às 11:54, Xavier C. Llano <
notifications@github.com> escreveu:

**Comment by gena** [comment]
@Efrain73, can you please check if the following version works fine for you: https://drive.google.com/file/d/14s74jPVyymV6kJTBm4P24ComcyuPYe-C/view?usp=sharing

**Comment by XavierCLL** [comment]
yes, I forgot that zip is not the latest version sorry, use the gena zip

**Comment by gena** [comment]
The above zip should be also available as 0.0.3 if you enable Experimental in QGIS, we're testing this right now
